export function buildFallbackGeminiPrompt({ jd, resumeMarkdown, analysis, candidateContext }) {
  return [
    `You are editing an existing cybersecurity resume for a ${analysis.roleType || 'Security Engineer'} role.`,
    '',
    'Constraints:',
    '- Do NOT invent experience, certifications, or projects.',
    '- Rewrite existing bullets only.',
    '- Preserve one-page formatting.',
    '- Optimize ATS alignment naturally using relevant cybersecurity terminology.',
    '- Keep tone concise, technical, and impact-focused.',
    '- Do not force keywords that are not already supported by the resume.',
    '- If a keyword is missing, only suggest it as a target if the candidate already has related experience.',
    '- If the candidate has internship-only experience, frame them as internship/early-career and emphasize hands-on work, projects, and tool usage instead of claiming full-time ownership.',
    '- If salary or job-research notes are provided in candidate context, never include them in the resume itself; use them only for tone and positioning.',
    '',
    `ATS Match Score (current): ${analysis.atsScore ?? 'N/A'}%`,
    `Strong Areas: ${(analysis.strongAreas || []).join(', ')}`,
    `Missing Keywords: ${(analysis.missingKeywords || []).join(', ')}`,
    `Add Now (truthful, high-impact items already supported by the resume): ${(analysis.addNow || []).join(', ')}`,
    `Remove or Deprioritize: ${(analysis.removeOrDeprioritize || []).join(', ')}`,
    `Update First: ${(analysis.updateNow || []).join(', ')}`,
    `Experience Positioning: ${analysis.experiencePositioning || ''}`,
    `Resume Focus: ${(analysis.resumeFocus || []).join(', ')}`,
    candidateContext ? `Candidate Context: ${candidateContext}` : '',
    candidateContext ? 'Use the candidate context only for truthful framing; do not paste it into the resume.' : '',
    '',
    'Instructions for rewrite output:',
    '1) Keep markdown format.',
    '2) Improve Summary, Skills, and Experience bullets using only truthful existing content.',
    '3) Prioritize missing keywords only where genuinely applicable to the current background.',
    '4) Include a short plan for what to update in Summary, Skills, and Experience first.',
    '5) If the candidate only has internship experience, clearly keep the resume honest and early-career focused.',
    '6) Do not add fake tools/certs/projects.',
    '7) If the resume is missing many JD items, keep the rewrite selective: highlight what is actually supported, and avoid trying to cram every JD keyword into the resume.',
    '',
    'Job Description:',
    jd,
    '',
    'Current Resume Markdown:',
    resumeMarkdown,
    '',
    'Return a revised resume strategy with clear update instructions, not a fake resume.'
  ].join('\n');
}
